### ISSUE TITLE
Add `resize: none;` for `textarea`

### ISSUE THREAD

**Issue by missingtrailingcomma** [siddharthkp/notes#3]
Right now the `textarea` shows the resize button, would it be better that the resize button is hidden?

**Comment by siddharthkp** [comment]
Good find! A pull request would be great :)

**Comment by missingtrailingcomma** [comment]
I've created an PR #5, would you please review it and see if it can be merged or it needs further changes? Thx :)

**Comment by siddharthkp** [comment]
Deployed, thanks 👍
